"""Initial migration

Revision ID: 5aa24f2165ce
Revises: 
Create Date: 2024-12-05 20:31:36.139681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5aa24f2165ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('students')
    op.drop_table('meetings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('users')
    op.drop_table('student_progress')
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receiver_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', mysql.ENUM('sent', 'read'), server_default=sa.text("'sent'"), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], name='messages_ibfk_2'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name='messages_ibfk_1'),
    sa.PrimaryKeyConstraint('message_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student_progress',
    sa.Column('progress_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attendance', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name='student_progress_ibfk_1'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], name='student_progress_ibfk_2'),
    sa.PrimaryKeyConstraint('progress_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.ENUM('teacher', 'parent', 'student'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('meetings',
    sa.Column('meeting_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time', mysql.TIME(), nullable=False),
    sa.Column('status', mysql.ENUM('scheduled', 'completed'), server_default=sa.text("'scheduled'"), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.user_id'], name='meetings_ibfk_2'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], name='meetings_ibfk_1'),
    sa.PrimaryKeyConstraint('meeting_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('students',
    sa.Column('student_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('grade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('progress', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.user_id'], name='students_ibfk_1'),
    sa.PrimaryKeyConstraint('student_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notification_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('delivered', 'sent'), server_default=sa.text("'delivered'"), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='notifications_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
